# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - bash: printf "NEO4J_USERNAME = neo4j \nNEO4J_PASSWORD = test \nNEO4J_BOLT_URL = \"bolt://neo4j:test@40.114.236.4:7687\" \nMONGODB_URI = \"mongodb://40.114.236.4:27017/schreddit\" \nJWT_SECRET_KEY = \"94a1bbc5f92730e7d49bf2389b1d1714afdcbf0e315492582d8f506a61f4e25e\" \nREDIS_DSN = \"redis://40.114.236.4:6379\"" > $(Build.ArtifactStagingDirectory)/backend/app/.env
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'SchredditRegistry'
        repository: 'backend'
        command: 'build'
        Dockerfile: '**/backend/Dockerfile'
        tags: '$(tag)'
